# Project Information
site_name: Lab note for UMD BIOI611
site_author: Shaojun Xie 
site_description: >-
  Lab note for BIOI611

# Repository
repo_name: Bix4UMD/BIOI611_lab
repo_url: https://github.com/Bix4UMD/BIOI611_lab.git 
#edit_uri: https://github.com/Bix4UMD/BIOI611_lab/edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 Shaojun Xie

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Bix4UMD

# Page Tree
nav:
  
  - Get ready for the course: 
    - Basic Linux:  basic_linux.md
  - Bulk RNA-seq
    - Prepare data: bulkRNAseq_lab.md
    - Phred score in FASTQ: FASTQ_PHRED.md 
      #- Basic R:      basic_r.md
    #- Basic Python: basic_python.md
   
    #- Intronduction:
    #- RNA-seq data analysis: s1_lab_RNAseq_lab.md 

 #- FAQ:
 #     - General Questions: general-questions.md
 #     - Troubleshooting: troubleshooting.md
 #- Reference: ref.md
 # - License: license.md
